vich_uploader:
    db_driver: orm

    mappings:
        phweep_image:
            uri_prefix: '/images/phweeps'
            upload_destination: '%kernel.project_dir%/public/images/phweeps'
            namer: 'Vich\UploaderBundle\Naming\OrignameNamer'
